apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-component-iydlbe
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-yfck-tenant/build-suite-positive-mc-mzhg/go-component-iydlbe@sha256:e234a79779029f300bafed0422284cb34b1c15873bfb4cc0ccb2b062364f3446
        name: my-go
        resources: {}
status: {}
