apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-iydlbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-iydlbe
    app.kubernetes.io/part-of: build-suite-positive-mc-mzhg
  name: go-component-iydlbefcyz
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: go-component-iydlbe
    weight: null
status: {}
