apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-iydlbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-iydlbe
    app.kubernetes.io/part-of: build-suite-positive-mc-mzhg
  name: go-component-iydlbe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-iydlbe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-iydlbe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-yfck-tenant/build-suite-positive-mc-mzhg/go-component-iydlbe@sha256:e234a79779029f300bafed0422284cb34b1c15873bfb4cc0ccb2b062364f3446
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
